# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  push-build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: |
          [
            { "id": "sonatype", 
              "url": "https://oss.sonatype.org/content/repositories/snapshots/", 
              "releases": {"enabled": "false"}, 
              "snapshots": {"enabled": "true" }
            }
          ]
        servers: |
          [
            { "id": "sonatype", "username": "${{SONATYPE_BOT_USERNAME}}", "password": "${{SONATYPE_BOT_TOKEN}}" }, 
            { "id": "github", "username": "${{GITHUB_ACTOR}}", "password": "${{GITHUB_TOKEN}}" }
          ]

    - name: "Maven Build & Deploy Snapshot to Sonatype OSSRH"
      if: ${{ github.event.repository.fork == false }}

      run: |
        mvn -P gh-push -B -e deploy

      env:
        SONATYPE_BOT_USERNAME: ${{secrets.SONATYPE_BOT_USERNAME}}
        SONATYPE_BOT_TOKEN: ${{secrets.SONATYPE_BOT_TOKEN}}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Maven Build"
      if: ${{ github.event.repository.fork == true }}

      run: mvn -B -e -Prun-its verify
